export const adminSidenavItems = [
  {
    id:'dashboard',
    name:'Dashboard',
    route:'/admin/dashboard',
    icon:'/assets/images/icons/dashboard.svg'
  },
  {
    id:'products',
    name:'Products',
    route:'/admin/products',
    icon:'/assets/images/icons/products.svg'
  },
  {
    id:'categories',
    name:'Categories',
    route:'/admin/categories',
    icon:'/assets/images/icons/categories.svg'
  },
  {
    id:'coupons',
    name:'Coupons',
    route:'/admin/coupons',
    icon:'/assets/images/icons/coupons.svg'
  },
  {
    id:'offers',
    name:'Offers',
    route:'/admin/offers',
    icon:'/assets/images/icons/offer.svg'
  },
  {
    id:'logout',
    name:'Logout',
    route:'',
    icon:'/assets/images/icons/logout.svg'
  }
]